"""
Q6 — Font glyph compression.
This file is regenerated by the notebook after training.
Architecture must match FontEncoder / FontDecoder in deep.ipynb.
"""
import os
import torch
import torch.nn as nn

_DIR = os.path.dirname(os.path.abspath(__file__))
MAX_PTS = 200


class _FontEncoder(nn.Module):
    def __init__(self, latent_dim=32):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv1d(2, 64,  3, padding=1), nn.BatchNorm1d(64),  nn.ReLU(),
            nn.Conv1d(64, 128, 3, padding=1), nn.BatchNorm1d(128), nn.ReLU(),
            nn.Conv1d(128, 256, 3, padding=1), nn.BatchNorm1d(256), nn.ReLU(),
        )
        self.fc = nn.Sequential(
            nn.Linear(256, 128), nn.ReLU(),
            nn.Linear(128, latent_dim),
        )

    def forward(self, x, lengths):
        h = self.conv(x.transpose(1, 2))          # (B, 256, 200)
        B, C, N = h.shape
        mask = (torch.arange(N, device=h.device)
                .unsqueeze(0) < lengths.unsqueeze(1)).unsqueeze(1).float()
        pooled = (h * mask).sum(2) / lengths.float().unsqueeze(1).clamp(min=1)
        return self.fc(pooled)                     # (B, 32)


class _FontDecoder(nn.Module):
    def __init__(self, latent_dim=32):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent_dim, 128), nn.ReLU(),
            nn.Linear(128, 256),         nn.ReLU(),
            nn.Linear(256, 512),         nn.ReLU(),
            nn.Linear(512, MAX_PTS * 2),
            nn.Tanh(),
        )

    def forward(self, z):
        return self.net(z).view(-1, MAX_PTS, 2)    # (B, 200, 2)


def encode(points, lengths):
    """
    points:  B x 200 x 2 float tensor (zero-padded outlines).
    lengths: B integer tensor (number of real points per outline).
    Returns: B x 32 float tensor of latent codes.
    """
    device = points.device
    model = _FontEncoder().to(device)
    model.load_state_dict(
        torch.load(os.path.join(_DIR, "encoder_weights.pth"), map_location=device)
    )
    model.eval()
    with torch.no_grad():
        return model(points.float(), lengths)


def decode(latents):
    """
    latents: B x 32 float tensor.
    Returns: B x 200 x 2 float tensor of reconstructed point coordinates.
    """
    device = latents.device
    model = _FontDecoder().to(device)
    model.load_state_dict(
        torch.load(os.path.join(_DIR, "decoder_weights.pth"), map_location=device)
    )
    model.eval()
    with torch.no_grad():
        return model(latents.float())
