"""
Q5 — Dice product prediction.
This file is regenerated by the notebook after training.
Architecture must match DiceCNN in deep.ipynb.
"""
import os
import torch
import torch.nn as nn
import numpy as np
import torchvision.transforms as T

_DIR = os.path.dirname(os.path.abspath(__file__))

# Unique product values — populated from training labels by the notebook.
# Shape: (N_CLASSES,) int array where element i is the product for class index i.
_UNIQUE_PRODUCTS = np.load(os.path.join(_DIR, "product_class_map.npy")).tolist()
_IDX_TO_PROD = {i: p for i, p in enumerate(_UNIQUE_PRODUCTS)}


class _DiceCNN(nn.Module):
    def __init__(self, n_classes):
        super().__init__()

        def cb(in_c, out_c, pool=True):
            layers = [nn.Conv2d(in_c, out_c, 3, padding=1),
                      nn.BatchNorm2d(out_c), nn.ReLU(inplace=True)]
            if pool:
                layers.append(nn.MaxPool2d(2))
            return nn.Sequential(*layers)

        self.features = nn.Sequential(
            cb(3, 32),
            cb(32, 64),
            cb(64, 128),
            cb(128, 256),
            cb(256, 512, pool=False),
            nn.AdaptiveAvgPool2d(1),
        )
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(512, 256), nn.ReLU(inplace=True), nn.Dropout(0.5),
            nn.Linear(256, n_classes),
        )

    def forward(self, x):
        return self.head(self.features(x))


_norm = T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])


def predict(images):
    """
    images: B x 3 x 128 x 128 float tensor, values in [0, 1].
    Returns: B x 1 integer tensor of predicted die-face products.
    """
    device = images.device
    x = _norm(images.float())

    model = _DiceCNN(len(_UNIQUE_PRODUCTS)).to(device)
    model.load_state_dict(
        torch.load(os.path.join(_DIR, "product_weights.pth"), map_location=device)
    )
    model.eval()

    with torch.no_grad():
        idx = model(x).argmax(dim=1)

    products = torch.tensor(
        [_IDX_TO_PROD[i.item()] for i in idx],
        dtype=torch.long, device=device,
    ).unsqueeze(1)
    return products
